#define USE_TWI
#define BACKWARDS_DIODES
#define ROWS 6
#define COLUMNS 14
#define MAX_TAP_DURATION 250
#define ROW_PINS { }
#define COLUMN_PINS { }
#define BOOTLOADER_SEC_SIZE_BYTES 512
#define LED_CONFIG { { PIN(B, 5), SHOW_CAPS_LOCK_STATE }, { PIN(B, 6), SHOW_LAYER_BIT_1 }, { PIN(B, 7), SHOW_LAYER_BIT_0 } }
